### ISSUE TITLE
Do you still slackline? If so, working on any tricks?

### ISSUE THREAD

**Issue by shama** [RichardLitt/ama#1]

**Comment by RichardLitt** [comment]
I do! I just got my slacklines out of storage, which is super nice, as I didn't bring them with me to Asia when I was there for a few months. I need to put them up on the Charles and start doing it more. I just set up a line on a lake in the Adirondacks a couple of weeks ago, it was ace. 

I'm not interested in tricks - I slackline because I like the balance and the meditative aspect. It's more about being calm, for me, and about having a beer with friends and something to do so that I don't feel bad just sitting around. 

You working on any?

**Comment by shama** [comment]
:+1: Nice! A line in the Adirondacks sounds amazing.

I definitely need to setup more often in visually appealing spots. I usually just setup at a nearby park and have a line setup at home.

I've been working on kneeling and sit poses on the line and just recently am able to balance w/o my arms well enough to juggle a bit :)

But glad to hear you're still slacklining and thanks again for getting me into it! It's taught me how to better focus and relax, quite a bit. :D

**Comment by RichardLitt** [comment]
Nice! I need to get better at juggling. Keep slacking man.
