### ISSUE TITLE
What's the best book you've ever read and why?

### ISSUE THREAD

**Issue by sindresorhus** [RichardLitt/ama#10]

**Comment by RichardLitt** [comment]
This is hard. Insanely hard. 

I reread books, all of the time. Some of my favourite books don't stand up, ten years later, or to a third reread. Some books are really important at certain points in my life, but don't resonate later. Right now, [Practice of the Wild](http://www.amazon.com/Practice-Wild-Gary-Snyder/dp/0865474540) wouldn't do much for me, because I'm not focused on ecology and wild community as much as I am thinking about writing and family. I'm reading [My Struggle](http://www.amazon.com/My-Struggle-Karl-Ove-Knausgaard/dp/0374534144/ref=sr_1_1?s=books&ie=UTF8&qid=1440186915&sr=1-1&keywords=my+struggle) right now, and it is changing a lot of how I think and what I think is possible in prose, but it is so depressing and pertinent to my life right now that I don't know if it will stand up to a reread, at all. I am currently on my 13th read through The Two Towers - and it's not as good as it was the first time I read it, although it opened my up to fantasy literature, as a whole, and let me think that there are beautiful things out there that can be written. 

I think the best book I've ever read has to be answered by a following question: what book best suited me? What book was right for me at the time, or showed me that certain things are possible? I think I am going to have to go with [The Book of the New Sun](http://www.amazon.com/Shadow-Claw-First-Half-Book/dp/0312890176/ref=sr_1_1?s=books&ie=UTF8&qid=1440187025&sr=1-1&keywords=the+book+of+the+new+sun). Because this book, above all other books, allows me to read it for fun, for pleasure, for a search for meaning, for it's writing style, for love (a friend suggested it to me, and I read it often to remember him). It appeals to my sci-fi side, my philosophy side, but doesn't have the mental challenge of reading better writers, like [Collected Fictions](http://www.amazon.com/Collected-Fictions-Jorge-Luis-Borges/dp/0140286802/ref=sr_1_1?s=books&ie=UTF8&qid=1440187093&sr=1-1&keywords=Borges+short+stories) of Borges, or the slapstick fantasy feel of something like [American Gods](http://www.amazon.com/American-Gods-Neil-Gaiman/dp/0380789035/ref=sr_1_1?s=books&ie=UTF8&qid=1440187119&sr=1-1&keywords=american+gods). It holds up well to a reread, and every time I start, I can't stop. So I'll say that book. It's for me.
