### ISSUE TITLE
Tell me about the first time you smoked a cigarette.

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/ama#11]

**Comment by RichardLitt** [comment]
There was a standing joke that I arrived two weeks early for some party, and just never left. I would litter the living room with cups with two or three bags of tea in them, and empty bowls that had been full of rice and grated cheese with soy sauce. I went through a 10 kilo bag in less than a month, and saw dozens of movies off of the IMDB best movies list. The green light that filtered through the algaeic fish tank woke me up in the mornings, when I woke up in the morning. I didn't pay rent, but I made promises to put up my friends whenever they needed for the rest of their life. 

"So, we're living together next year, right?" Alex asked.
"Ugh, yeah?"
"So you're paying my rent right?"
"Fuck."

It was into this sort of environment that Flo stumbled. Flo was a German couch surfer, and he had a girlfriend with her, I think her name was Anna. There were a lot of couch surfers in those days - I was obviously one, but a four-month stint can't really be called couch surfing anymore. We called Flo the machine. He out drank, out smoked, and out weeded even our most valiant warrior, Jamie, who lived in the larger room amid piles of bikes and boxes and records and a giant stolen advertisement for a hotel around the corner that he had used to sled down Arthur's Seat one winter. Flo was over six feet, and built like an ox. He had long dreds, and worked construction in the winters, and seasonal job sin Norway in the summers, after dropping out of his Philosophy degree because they didn't know anything about real living. I found out months later, when I hitched to Duisburg to see him, that he bred beta fish and had a penchant for getting high before going to work. 

Jamie had a small contraption he used to roll cigarettes; it was a small tin box that had a long rectangular opening in it, and you'd put the paper in, with a filter, and it would roll you a perfectly cylindrical cigarette. It invariably never worked. Flo had a better plan; he put papers between his thick fingers, added a dash of tobacco, licked the top bit, and with a flick, rolled the whole thing into something resembling a joint, when it wasn't a joint straight out. We had a single, [In the Year 2525](https://www.youtube.com/watch?v=yesyhQkYrQM), that we had melted the edges of so that it turned into a small salsa bowl with a hole in the middle which we patched with black duct tape. We used this for an ashtray; Flo had it in his lap, permanently. 

"I'm here to see the dirtiest toilet in Scotland!" He meant [this one](http://www.gonemovies.com/WWW/XsFilms/SnelPlaatjes/Trainspotting2RentonToilet.jpg), from the movie Trainspotting.

It was somewhere on either side of this statement that I realized that Flo was, in my words at the time, pretty fucking awesome. 

But there was a distance. I was a drop out, too - I had taken a year off to do the Appalachian trail, and here I was, sitting on a couch in Edinburgh. I'd go back in a year, but so might Flo. I didn't have dreds, much less muscle, but I liked Germans and I understood the need to see real life and not just sit in a Philosophy class. I had dropped out of my English degree and switched to Linguistics because I started taking walks every afternoon instead of going to class. Flo and I were similar. 

But there was a distance. Oh, that distance. 

This was the clincher: I hated smokers. I didn't like the smell of tobacco. I didn't like the people who were so weak that they needed it. I didn't like the crazy eyes of homeless men asking me for fags on the street; I didn't like the way a smoker came into the room and you knew before you saw them. I didn't like associating myself with lowlifes or lower class workers or drug addicts. Marijuana, cocaine, mushrooms - these were all just as bad as tobacco to me. 

"Flo, that's just a movie set. Anyway, the movie was shot in Glasgow."
"Echt? Fuck!"

_God damn it_, I thought. _I'm an asshole. I'm a pretentious fucking asshole._ This realization was followed shortly by thought, _I don't have to be._ 

I reached for a pack of drum and a roll. I asked Jamie to teach me how to roll. I wanted to know what it was like to smoke, to do something with your hands instead of sitting around fiddling with old mugs stuffed with tea bags. I wanted to know what it was like to be an addict. I wanted to know if I could close that gap, with me as a pretentious non-smoker on one side, and my friends on the other. 

Two nights later, I was outside the Black Bull. We had gone there because it's where Ewan MacGregor jumps after running down Princes Street in the opening credits of Trainspotting. I'd never been before. I was outside, coughing away at a cigarette. A guy asked me if I smoked normally. 

"This is my second cigarette," I said.
"Put it out, now." The man said. He had a large black beard, a hat, and he wasn't smiling. 
"What?"
"I'm trying to do you a favor. Put it out now, and never smoke again."
"Nah. I'll finish it."
"Your funeral."

It's been half a dozen years since then. I've smoked my way across three continents. I once calculated I've smoked at least a couple of miles of cigarettes. 

I still think of that guy in the Black Bull every week or so. I'm going to go think of him now, because when I'm done writing this, I'm going to go smoke outside this cafe. That's what I do now. It's what I did last night; I watched _A History of Violence_, an incredibly powerful film noir with Viggo Mortensen, and felt so drained and full of the movie and identity that I immediately went out to The Burren, a bar here in Davis that has Irish music, and sat there alone with an Allagash White just to have something to do. The bar was full, but I sat there for three or four songs, went out in the breaks to smoke, tipped the band and decided to see what was going on in Toad, a bar right next to my house with life music. There was a jam band playing, psychedelic stuff, a Bob Dylan cover. I started talking to a tall man with a black beard and a shirt that I guessed was Yanni, Frank Zappa, Freddy Mercury, before the man told me it was Groucho Marx. I asked him where he was from, and he said Valencia. I mentioned my times over there.

Then, at one point: "So, you picked up smoking in Europe, I see."
