### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [RichardLitt/ama#13]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by RichardLitt** [comment]
Spain is alright. I don't know how people outside of Spain think about Spain. 

I know that I've been to Barcelona a few times - I think of that as Catalyuna and not Spain, probably because I lived in Scotland for a long time and so am very sympathetic to regional movements. Barcelona was fun, but I haven't been to Madrid or anywhere else yet. I've known a lot of Spaniards, and they're a mixed bag, but many of them were great and I remain friends with. I've got no real interest in going back - I lived in Malta for 8 months and don't feel like I need to see more Mediterranean countries at the moment - but maybe someday I'll visit again.
