### ISSUE TITLE
Who's your favorite superhero?

### ISSUE THREAD

**Issue by arthurvr** [RichardLitt/ama#15]

**Comment by RichardLitt** [comment]
This is tough. 

I'm a big fan of [Dr. Manhattan]. He's the obverse of Superman; he's also a superhuman, but he's from Planet Earth, and he can't fit in just the same. 

![Dr. Manhattan](http://files.umwblogs.org/blogs.dir/7524/files/2013/02/drManhattan.jpg)

And then there's V, from V for Vendetta, but to be honest I think that the whole anonymous thing has made me a bit less empathetic towards his single-handed struggle towards the state. Also, at times he was callous to other's emotions, which isn't the coolest. 

Both of these men are super men trying to be men; I saw on reddit someone sum up DC saying that their heroes are gods trying to be men, but Marvel is men trying to be gods. If it came to a fight, I know whose side I would be on, which is why I am going to be fairly uncontroversial and say Tony Stark is the best. 

Tony Stark is wildly narcissistic, arrogant, hot tempered, and at times, stupid. But every time he stops and has a crisis, he doesn't drag his feet about it; he figures out a solution and makes some shit happen. He also has a sense of humor, which is better than most superheroes, and is overall fun and enjoyable to read and watch. 

So there you have it. Iron man. 

![Stark](https://24.media.tumblr.com/tumblr_m7p02z7JBQ1qajc4eo1_500.jpg)
