### ISSUE TITLE
What career paths are open to someone with skills in foreign languages and programming languages?

### ISSUE THREAD

**Issue by CarlMungazi** [RichardLitt/ama#17]

**Comment by RichardLitt** [comment]
Any information-based career path is open given those prerequisites. This includes programming and translation, the two obvious ones, but also includes anything which can use those skills. For instance, being a small shop owner might require these skills if online presence is important, or if knowing multiple languages is. 

To be more honest, though, I don't know what a 'career path' is. It's a very nebulous concept that I think has been inculcated into the modern era through universities wanting to justify themselves to their increasingly rich customers (students), and through large companies trying to instill in their employees the idea that working long hours over many years will somehow end at a nice solution for them. Neither of these things are true: universities don't need to exist to teach students about the right skills they might need in industry - they should exist to explore learning - and large companies don't have their employees best interests at heart -- they have their stakeholders and investors best interests at heart. Instead of looking for a career path, I would look for a vocation that pays well in the present and doesn't seem like it will go away soon enough to make the cost of learning it higher than the profit gained from it. 

Put a third way, if you like foreign languages and programming languages, you should have the skills you need to find innovate ways to continue learning and using them, instead of using them towards some other job.
