### ISSUE TITLE
Why do you travel?

### ISSUE THREAD

**Issue by sindresorhus** [RichardLitt/ama#2]

**Comment by RichardLitt** [comment]
My back hurt this morning. It still hurts. I bought my bed, along with some lamps, a set of shelves that looks like a dozen milk crates tied together, a tall dresser, and a coat rack for around $200 from Matt, who used to live in my apartment. He left two coffee capsules for his coffee machine on the shelf in the kitchen, too, but I didn’t buy those directly. The set of milk crates fell down two days ago - I was attempting to put the 40 or so records I own onto the top left corner, where I had an old black box full of mementos (some of which are so old I’ve forgotten what they were supposed to remind me of) and some old notebooks and a Harvard binder. I had got the records back after lending them to my old flatmate Kim for safe keeping, over a year ago, in Brooklyn. Three of them are, I fear, irreparably water stained. Kim didn’t mention this to me, but it’s probably not her fault - that apartment had central heating for the whole building, and the humidity in the winter was so bad that I slept with a single top sheet. Around the top of the water pipe going to the second floor the plaster was peeling, turning a slight yellow color. One night, the people above me were having such a good time having sex that plaster fell onto an open record. I think it was the National’s ‘Trouble Will Find Me’, which I had been playing on repeat for months, since I bought it when my sister and brother-in-law visited for a couple of weeks while they struggled to get back to Geneva. This was hard for Daniel, my brother-in-law, mi cuñado, as he was from Colombia. Once, when I first met him, he told me as we walked past the university on the upper west side of New York that people often spelled it wrong - Columbia, as if he came from an Ivy league. I called him my coñado, for a while, too, not knowing that coño in Colombian Spanish is essentially calling him a cunt. I learned and my bruises started to heal. My back hasn’t, though - the bed I bought sags in the middle, and I have been sleeping longer recently because I am trying to quit cigarettes, which means I wake up at 4 am wondering what I am doing in Boston and why I didn’t move to Berlin, and then I forgot to go running at 6am along the Charles, which is the only time I can run long distance because it is cool enough that I don’t sweat too much and I forget that I should care about running and for a short while, I just run. I started running long distances seriously when I was in Hong Kong a few months previous, after rereading ‘What I Talk About When I Talk About Running’, by Murakami, and after learning that I can listen to podcasts while I run and stay mentally active instead of just listening to pop music and constantly wanting to change the station or the song, or speeding up my pace because, even if the beat doesn’t change, I want to run faster because who can listen to songs that extoll sex and love without thinking ‘Fuck yeah I want that, too’, and run a bit faster. But my lungs wouldn’t be able to sustain it - I was smoking a pack a day that week, or month, I never really bothered to keep too much tabs on it. So I’m quitting because I want to be able to wake up at six and then to start coding by eight. Right now I am unemployed, functionality - I have an open source project I was working on for MIT, but our funding temporarily ran out, and this is the first time in my life that I have savings and don’t really need to work, so I’m taking my time and just enjoying what I am doing with my life. It isn’t so bad. It means that I sleep until 11am, though, which means that I am up until 1am reading Lord of the Rings for the 13th time (that’s not hyperbole), and so my back hurts. My father’s back hurts, too - he tells me it comes from stress. I wonder if mine hurts because of the stress of living here, on this bed, in this room, surrounded by my books and with my records slotted into the bottom right compartment of my crate-like bookshelf. 

At 4 am, which is approaching, I think to myself: Shouldn’t I be traveling? 

I first left the States when I was around 12. I went for a long weekend to Vancouver, flying five hours by air from Bradley Airport in Connecticut, a minor airport that no one really uses unless they live in the vicinity of Hartford, and once, driving down the highway (or being driven by my father), we had a traffic jam because the road was briefly closed as President Clinton was coming by in a helicopter. I remember he was President because I remember him being sworn in in 1992, while I sat on the granite counter of the extension of the house I spent my first years in, watching my mother make cookies and churn the butter (I used to eat it by the stick), looking at the old wooden shelves behind her. The house was built in 1710, although it said 1610 on the side, and I couldn’t imagine something that old at the time and not feel wonder. Revolutionary War soldiers hid in the basement, and the house was build by the grandfather of Aaron Burr, a vice president who shot Alexander Hamilton in a famous duel and tried to secede from the Union with some of the more radical Whigs. I think he ought to have just gone to Canada - when I landed in Vancouver, I was instantly in love with the foliage, and the light, and the way things were. I was in love with being on my own in a strange country, without my family around me, free to go to bookstores and spend strange currency on books that I would then struggle to carry home. I took pictures, and I had them developed - I still have them here, in my black box on the shelf. In one, I am writing using an ink pen in an new leather journal, because I thought that is something one does when one is a man of the world and a traveller. I still think so. On my flight to Monterey, two weeks ago, when I went to see if I could get more funding for my project and to meet new people in my field, where I had a great time swimming in a wet suit, a new experience, with seals in the kelp forests, and where I had some wine on the beach at night by the fire and thought about when I first started smoking in college in Edinburgh and a man with a beard standing outside the Black Bull  Inn, which was in the movie Trainspotting, told me to put it out immediately, save myself the hassle, but I didn’t listen (and I should have), I spilled ink on myself ten minutes into the flight because my pen exploded in my hand while I was trying to write something down, something dreadfully important, probably about how great Knausgård was and how I wish I knew Norwegian and how I need to finally read Proust, and wondering where my copy had gone - I know I had lent it to Jennifer, who used to live across the road from me in Arden Place in Edinburgh and lived with Therese who I briefly dated for a second but didn’t get along with because I was too silent and I hit on another girl in the student theatre and Therese was from Germany and I thought that a language barrier meant something at the time, but I don’t now, and I told her to come visit me in Boston when she comes here next. Jennifer told me she gave my copy of On the Road, which was originally my older sisters, to her ex boyfriend in London, and I probably won’t see it again as that would be awkward, and she told me this as we drank wine together on my birthday three years ago in Paris when I was on the way to see my sister, and I laughed about it because I was young and I had just been reciting poetry and I had absolutely no money to my name whatsoever but I knew where to hitch a ride out of Paris and in the morning I did just that, and got to Geneva before dinner to see my sister and my cuñado (not coñado), of course. I remember on the flight to Monterey I also pierced the skin on my nose when I tried to rub my tired eyes and my thumb slipped, and the nail took off a section of skin and caused me to bleed, and I felt stupid, and the entire conference I felt a bit stupid, especially when after snorkeling I took off my wetsuit and dove into the water but dove too shallow, and my nose hit the bottom and the sand rubbed off the scab, and I was bleeding from the face, like my father was when I was four and he dove into the pool, or like I was when I got punched in the face by some random neds in Edinburgh before I went to Berlin for the second time instead of going to my graduation because I had a paper to present and I wore shades the entire conference because I couldn’t see otherwise. But I loved Canada, and I loved the fact that the paying for things with different money and the story I had to tell there as I was who I was and the stories I could tell others about who I was there were great. I remember meeting a girl from Cyprus in the line who was beautiful, and feeling pensive on a cruise through the harbor, and being embarrassed when I was asked if I would like chicken or salmon for dinner by my host family’s mother, and that she knew I didn’t like making decisions, but I did, I was just trying to be nice, and almost ten years later I had a similar conversation with an old man with long hair who ate fish once a month when the moon was full and made his own blueberry wine and lived in Victoria across the bay from Vancouver. I met him because I was hitching from San Francisco with my Belgian friend, also a developer, and we decided to go see something new. I brought the remnants of the pink guitar we hitched with back with me to Germany when I moved there, and I remember telling Bernulf about them, an old man I met outside of Stuttgart who made Erdberry wine and had the best stories, and woke me up with Deep Purple’s ‘Highway Trucker’, and also had a beard and a great laugh and a snort like a cow and told me his English was bad because he had to ask if he used the word ‘pylon’ correctly to describe a covered bridge. I remember I slept on a bed he made for his son, with some magazines near it and urns and bottles and vats of fruit slowly decaying on the other side of the room, and I woke up and my back hurt a bit then, too, but it didn’t matter, it was the fall in Germany and I was going to Leipzig from Geneva to meet an old friend of mine from Edinburgh, originally from Northern Ireland, who travelled to, and we would talk about things. I left my gift of triple-distilled pear schnapps with her, and I’ve never forgiven myself for it. I think I’m still traveling because I want to get that bottle back. I had a drink that was similar when I was in Hong Kong, seeing my ex-fiancée from Beijing who I met in New York who was and is really beautiful, who I just saw when I went to get my records, and she opened the door for me after I had been sitting on a bus for five hours and a train for two before that, and I was tired of traveling and wanted to be back in my room and working on my projects and reading Lord of the Rings, but she greeted me with a smile. She asked me how I was and where I had been, and I began to tell her. And I thought to myself, “Oh yeah, this is why you travel, Richard.”

**Comment by sindresorhus** [comment]
Thanks for sharing @RichardLitt! Interesting read :)

**Comment by sindresorhus** [comment]
@stoeffel Maybe something for awesome-ama-answers.

**Comment by stoeffel** [comment]
@sindresorhus definitely. 
@RichardLitt Thanks for taking the time to share this!

**Comment by RichardLitt** [comment]
I figured why not have some fun. :)
