### ISSUE TITLE
What are you working on and why?

### ISSUE THREAD

**Issue by sindresorhus** [RichardLitt/ama#5]

**Comment by RichardLitt** [comment]
It's interesting to me that this is an incredibly difficult question for me to answer. 

### Beagle

I don't have a full time job right now. I haven't had one for a few months, since my grant for [Beagle](https://github.com/BeagleLab/beagle) ran out. Beagle is a pretty interesting technical solution to a problem; how do scientists share their research while they are researching, and how can we identify interesting parts of papers and HTML and share them between researchers and labs while minimally impacting existing workflows. The answer is a [Hypothes.is](https://hypothes.is) like annotation scheme, in a Chrome extension, which works on re-rendered PDFs using PDF.js and on HTML pages. I've basically built that, but the backend - currently Mongo, eventually IPFS - needs some more work. I used React and Browserify on the project, and had a lot of fun and difficulty figuring out how they work together.

I thought and said that I would keep working on it, as an open source project, when  I wasn't paid, but this hasn't yet been born out in any significant way, which makes me feel shamed and guilty and also a bit capitalistic, which isn't something I'd like. There's a few things in Beagle I need to figure out to get it working - mostly, how to work with MongoDB, which is just seriously hard for me, and I haven't figured out how to get past that hurdle. It's difficult for me to sit down in the morning, without anyone really asking me to, and tell myself I am going to learn how to deal with a system I find mentally strenuous, for a project which I project will take weeks for me to finish. I wish it wasn't that way, but it is. I've been trying to figure out how to get around this block.

### Life & Highpointing

Since I stopped working on Beagle daily, and found myself in a liminal state. For the first time in my life, I have a good amount of savings, and no direct need to actually go and find work. I just turned 27, so you think this would have happened earlier, but I've been historically pretty bad at saving money up, and I've also got student loans so large that I haven't been able to afford to take time off. At the same time, I have had some things happen which impacted my productivity and my ability to actually take a full time job - without going into too much detail, I've had to spend a lot of time working on being an arbiter between different family members with drastically different lifestyles. That, combined with a lot of what people would call "soul searching" -- aka, taking time off to think about life, the universe, everything, and where my loyalties and time ought to lie --- has meant that I basically haven't been afforded the ability to focus too heavily on any one project. On several occasions, I've had to pull out of projects temporarily, or drop them entirely, because the stress was just too high and I found that I couldn't dedicate myself to thinking too heavily about anything code related for more than a few hours a day. 

I've tried to accommodate for emotional and familial turbulence by balancing out other non-work concerns. Basically, this means I have been making sure I get enough time around friends and that I'm looking after myself while I go through this phase. This has been tremendously fun for me to focus on; not only do I get to write myself essentially blank checks as far as seeing old friends I haven't seen in a while, but I also get to take the time to really take stock on how I am doing physically. I've started going to a bouldering gym every day, and I ran my first half marathon a month or two ago. I'm working on my endurance by running, my mobility by stretching and bouldering, and also my cardiovascular health by quitting smoking. I just started a new project a month ago, too; I'm going to the highest point in every state. This means I get to go hiking with friends. Just this past weekend I hiked to the top of Tennessee in the beautiful Smoky Mountains, and to the top of North Carolina on Mt. Mitchell, the highest peak this side of the Mississippi, and I drove to the tops of Georgia and South Carolina (they were pretty small hills). Next week, I hope to climb Katahdin in Maine, and maybe Mt. Marcy in New York. I'm enjoying getting out in nature, and the list-ticking aspect of going to each state affords me the possibility of seeing friends all over my country, and going to new places for no other reason than to have time to think and enjoy seeing something new. 

### Projects

However, I'm not very good at relaxing, even when I am trying to make sure that I do alright. So, I've still got a few projects here and there I am working on. Just recently I began working part time on [IPFS](https://ipfs.io/), which is one of the coolest projects around, building a distributed internet. I'm helping out with logistics, community management, code checking, tooling, and front end work. I'm very happy to be a part of this awesome team and I really enjoy the fact that it is distributed, remote, and not too heavy time-wise. I 100% think the product is amazing, and it is a great opportunity for me to learn a ton about things I don't know much about - the internet as a whole, protocols, working with a distributed team (an actual team, not just my normal solopreneur projects), and cryptography. 

I have a markdown file with around ninety other projects I have on my plate - some cold, some hot, some shelved, some not. Without mentioning them all, here are a few I am working on: 
- I still do [The User Is Drunk](http://theuserisdrunk.com) reviews, because it is easy, good money, and I enjoy the work - it gives me an excuse to have some beers with friends without worrying too much about taking time off from reading my books or working on projects. I keep thinking about closing it, but I don't really see a reason to at the moment.  
- I closed [The User Is My Mom](http://theuserismymom.com) due to lack of reviews and the trouble with maintaining it - there were a few parties involved, and streamlining the process wasn't worth the effort.  
- I recently founded [Word Hoard Press](http://wordhoardpress.com) in one day, the only literary press I know of that publishes original work by modern authors in Old English or other extinct Germanic languages. This didn't exist, and I wanted it to, and I don't care much if no one ever submits to it. I'm glad that it exists. That's reason enough for me to have made it. I might work on some pieces and submit them to, myself, I guess. 
- I'm planning Expedition Recursion, for next summer, where I and a couple of friends, one of whom is an expert in Arctic travel, will go to the most embedded lake-island system in the world, on Victoria Island in northern Canada. This is going to be a lot of effort, and incredibly dangerous, but I've got to do it, for me. I've always wanted to be an adventurer, and every time I get the drive, I need to follow it through to the end. I did this when I bought Maya, a 25" Folksong yacht, in Sicily, and learned to sail by sailing her to Malta when I moved there. I did the same when I hitched around Europe, and the same when I moved to San Francisco to see if I could make it as a "developer". Sometimes you have to just do things. 
- I maintain [git-flight-rules](http://github.com/k88hudson/git-flight-rules), [awesome-scifi](https://github.com/sindresorhus/awesome-scifi/), [awesome-fantasy](https://github.com/RichardLitt/awesome-fantasy), [endangered-languages](https://github.com/RichardLitt/endangered-languages) and [awesome-conferences](https://github.com/RichardLitt/awesome-conferences) because I think that they should all exist and be worked on. The scifi and fantasy projects are more for me than for anyone else; I frankly just like knowing what I should read next and what I like. Git Flight Rules is a great idea, and it wasn't being supported as much as I would have liked, so I begged until I could work on it, and now I just do a ton of reorganization and add to it whenever I can. Endangered Languages is part of a much wider effort on my part to help dying languages, and I've got a paper in review right now for an academic conference about it, and have more stuff to do with this than I really can afford to take on. I keep meaning to make a small website out of awesome-conferences, but Lanyard frankly already does an OK job in this market. I would like to do more for [Contribute-md](https://github.com/contribute-md), but I think I am alone in that organization. 
- Science - I do a lot of random science projects, and am still working on things that I hope can eventually become my thesis. I'm a Masters student in Computational Linguistics in Germany, and I really hope to finish this some day, but I need to find an advisor and begin writing a thesis at some point. I've just hired a lawyer to help me (and my extended family, who I asked to join me) in proving our German citizenship. After hours and hours of personal research, I realised my great grandfather Frederick was born a few years before his father, Ludwig, naturalized as a US citizen, meaning he was a dual citizen. So, I am too. The lawyer is working on getting all of the birth certificates and the like to prove this. I really hope this works. 

### Writing

Mainly, I've been thinking about writing a lot. I've got a few novellas or short stories I am working on, and I try to write every day, if only for a blog or a journal entry. Most of my stories are fantasy, and I'm hoping to eventually be able to publish them somewhere. Not an hour goes by that I don't think I ought to be writing, and I've been that way for as long as I remember. So, I've been working on those a bit. I've also got some other projects in the works; reworking my blog, for one, and then building both [58litres.com](http://58litres.com) and [antinomadic.com](http://antinomadic.com), the first a project outlining everything I carry with my as a digital nomad, the second a project talking about the downsides of being a digital nomad. Kind of contradictory, but I wouldn't have it any other way. 

I also read. I am always reading. I've read over 50 books this year, and the more I read the more I want to keep reading. Right now I am reading The Book of Lost Tales by Tolkien, because I want to actually finish it, and the third volume of My Struggle by Knausgaard, which is easily one of the best books I have ever read. This weekend, on the plane to North Carolina, I read Fahrenheit 451, which was amazing, and Pride and Prejudice and Zombies, which was much better than the original work that lacked zombies. I've started buying books again, now that I live in Boston, and so I have a ton to catch up on, and I'm trying as hard as I can to. 

I also read poetry, every day. I record myself reading the poems aloud, because I find that I enjoy poetry much more if I read it slowly instead of at my breakneck normal pace, and because I like making recordings to share with friends. It makes me feel a bit more connected to people. 

### Summary

So, that's me, pretty much. A few open source projects, a few projects just sort of continuing because they aren't strenuous, then IPFS and Beagle. Bouldering, running, Tai Chi, and hiking as much as I can. Reading poetry, writing and reading. Going on dates occasionally. Thinking about my father and my mother, what it means to be a good son, nephew, brother. Meditating, working on linguistic and computational science. Trying to enjoy each day for what it is.

**Comment by sindresorhus** [comment]
:+1: Thanks for sharing :)
