### ISSUE TITLE
What's your favorite language?

### ISSUE THREAD

**Issue by sindresorhus** [RichardLitt/ama#7]

**Comment by RichardLitt** [comment]
This is kind of like asking what is your favourite type of stained glass. Not what is your favourite window, of which this one might be a winner: 

![Richard III](http://kingrichardarmitage.rgcwp.com/files/2012/08/RIII-and-Queen-Anne-Neville-Stained-glass-window-at-Cardiff-Castle.jpg)

But what is your favourite section. And you have to judge this without being able to look through the window, it's the idea of a window. You're asking me to remember all of the windows I've seen, pretend I am looking through them at 2 am when it is dark outside, and to choose which pane is my favourite. 

Language is a scaffold, and choosing which scaffold works the best or is the most aesthetically pleasing is subjective. For me, it depends on the building. At times, I love Japanese because I love the Haiku as a form, and that's only really possible and beautiful with a syllabic language with more constrained phonotactic rules than English. I also love their tradition of haikus almost as much as the form itself - it's who wrote them and why, and how they lived that interest me. The calligraphy of Japan and China can't be beat, except perhaps by Arabic scripts you see on some buildings. I mean, this is the Dome of the Rock, and some people can read this:

![Dome of the Rock](https://newgottland.files.wordpress.com/2012/09/brian-creese_dome-of-the-rock.jpg)

I've studied a lot of languages. I've read the Aeneid in Latin, and a lot of the Odyssey in Greek. I wouldn't say that I love either of those languages, although it is possible to do wonderful things with them, particularly amazing things with meter. But I prefer the intricacies of Skaldic and old Germanic verse to the somewhat pounding strains of meter done in classical Mediterranean verse. 

I've yet to find a constructed language I really love. 

My favourite language may be English, because of it's varied history. But when I look at it, there's so much variation that I can't keep a hold on how the pane in the window actually looks. So I am going to choose Middle or Old English. But really, there's something beautiful, to me, about all Germanic languages, in general. I'd like to learn Norse, Norn, Icelandic, Swedish, Danish... And I practice German daily, and occasionally go back and translate Old English poems. None of these languages are different enough for me to say one is better or more pleasing than the other. But I hope to choose, some day. 

![Battle of Maldon](http://research.uvu.edu/mcdonald/anglo-saxon/warfare_files/408e9de1.jpg)

My favourite couplet in all of the world is from the Battle of Maldon, a small piece of literature for which we've lost the beginning and the end, but it is probably the finest in all of our remaining pieces of Old English. 

Hige sceal þē heardra,      heorte þē cēnre,
mōd sceal þē māre,      þē ūre mægen lytlað.

I can't think of anything more beautiful than that. I don't want to go through and describe all of the context, because you asked me about the language, not the poetry, but that's my favourite. There.
