### ISSUE TITLE
What would be the perfect human language?

### ISSUE THREAD

**Issue by sindresorhus** [RichardLitt/ama#8]
Would it be something created from scratch? Or would it be an evolution or inspired by an existing language?

**Comment by RichardLitt** [comment]
It depends on your definition of perfect. There have been a lot of constructed language attempts to make perfect languages - by which one means easily learnable, like Esperanto, or maximally expressive, like Ithkuil (there's a great article on this, in the [New Yorker](http://www.newyorker.com/magazine/2012/12/24/utopian-for-beginners)), or minimally ambiguous, like Lobjan or Loglan. Some constructed languages are made to be the most aesthetically pleasing - Elvish was one of these. 

No language could possibly fit all of these categories; perfect, then, is an impossible goal. Language evolution itself is tricky, and doesn't tend to progress towards any sort of minimal complexity or maximal expressiveness. Much like living organisms don't become superbeings through natural selection, languages fit the niche they are used in, and have their own particular weirdnesses that cause them to split and change. 

It's impossible to have an objective view of a language, too; you either speak it natively, or you don't really know how it can be shaped a lot of the time. For me, English isn't that bad of a language. But that's because I know it fairly well.
