### ISSUE TITLE
What do you think about dinosaurs?

### ISSUE THREAD

**Issue by sindresorhus** [RichardLitt/ama#9]
What's your favorite dinosaur?

**Comment by RichardLitt** [comment]
I love them. When I was three I wanted to be a paleontologist, and that dream never fully died. One of the highlights of my entire life was sitting in an evolutionary anthropology conference at Oxford, reading a paper on Hadrosaur horns, because they are hollow and we think that they used them to make massive boom-like calls (like a trumpet), and I was going to be able to use this information in a paper I was writing on the evolution of laryngeal air sacs in humans (I did eventually publish [this](http://www.burntfen.net/merecat/wp-content/uploads/2012/01/A-Reanalysis-of-Anatomical-Changes-for-Language-Re-Dating-the-Loss-of-Laryngeal-Air-Sacs-in-Homo-sapiens.pdf)), and I realized I was effectively studying dinosaurs for a living. I failed to focus on anything else for the remainder of the conference, and that night almost fell into the canal across from Maldon College while I was celebrating with my friend over drinks.

Because of this, I think my favorite dinosaurs are probably Hadrosaurs, particularly _Parasaurolophus_: 

![Hadrosauric!](https://s-media-cache-ak0.pinimg.com/736x/2c/9f/f9/2c9ff97a85bca666233bc930adb15d79.jpg)

However, I am also partial to Plesiosaurs, another animal that can only be defined as "Majestic as all hell":

![Plesiosaurid](https://franceshunter.files.wordpress.com/2010/01/plesiosaur.jpg)

While we're on the subject, the kid's book I give away the most (at least twice or thrice now) is Dinotopia, which is the best series of books ever, because humans and dinosaurs live together. I highly recommend it:

![Fuck yeah](https://i.ytimg.com/vi/MrZ9GA-hiPI/maxresdefault.jpg)

Yeah, that's a hadrosaur on the far right. Hells yeah.
